{
    "attributes": [
        {
            "allowed_chars": null,
            "allowed_choices": null,
            "autogenerated": null,
            "channel": null,
            "creation_only": null,
            "default_order": null,
            "default_value": null,
            "deprecated": null,
            "description": "GroupName is the name of the group that this rule must be associated with.",
            "exposed": true,
            "filterable": true,
            "foreign_key": null,
            "format": "free",
            "getter": null,
            "identifier": null,
            "index": null,
            "max_length": 31,
            "max_value": null,
            "min_length": null,
            "min_value": null,
            "name": "key",
            "orderable": true,
            "primary_key": null,
            "read_only": null,
            "required": true,
            "secret": null,
            "setter": null,
            "stored": true,
            "subtype": null,
            "transient": null,
            "type": "string",
            "unique": null,
            "uniqueScope": null
        }
    ],
    "children": [],
    "model": {
        "aliases": [
            "ap"
        ],
        "create": true,
        "delete": true,
        "description": "AuditPolicy is an audit policy that consists of a set of audit rules. An audit policy will determine that types of events that must be captured in the kernel.",
        "entity_name": "AuditPolicy",
        "extends": [
            "@base",
            "@described",
            "@identifiable-pk-stored",
            "@metadatable",
            "@named"
        ],
        "get": true,
        "package": "Squall API",
        "resource_name": "auditpolicies",
        "rest_name": "auditpolicy",
        "root": null,
        "update": true
    }
}