{
    "attributes": [
        {
            "autogenerated": true,
            "description": "ID is the identifier of the object.",
            "exposed": true,
            "filterable": true,
            "format": "free",
            "identifier": true,
            "name": "ID",
            "orderable": true,
            "read_only": true,
            "type": "string"
        }
    ],
    "model": {
        "delete": true,
        "get": true,
        "update": true,
        "rest_name": "@identifiable-nopk-nostored"
    }
}