{
    "attributes": [
        {
            "autogenerated": true,
            "description": "Creation date of the object.",
            "exposed": true,
            "filterable": true,
            "name": "createTime",
            "orderable": true,
            "read_only": true,
            "stored": true,
            "type": "time"
        },
        {
            "autogenerated": true,
            "description": "Last update date of the object",
            "exposed": true,
            "filterable": true,
            "name": "updateTime",
            "orderable": true,
            "read_only": true,
            "stored": true,
            "type": "time"
        }
    ],
    "model": {
        "delete": true,
        "get": true,
        "update": true,
        "rest_name": "@timeable"
    }
}