{
    "attributes": [
        {
            "allowed_chars": null,
            "allowed_choices": [
                "AWS",
                "Aporeto"
            ],
            "autogenerated": null,
            "channel": null,
            "creation_only": null,
            "default_order": null,
            "default_value": null,
            "deprecated": null,
            "description": "providerType specifies the cloud provider.",
            "exposed": true,
            "filterable": true,
            "foreign_key": null,
            "format": null,
            "getter": null,
            "identifier": null,
            "index": null,
            "max_length": null,
            "max_value": null,
            "min_length": null,
            "min_value": null,
            "name": "providerType",
            "orderable": true,
            "primary_key": null,
            "read_only": null,
            "required": null,
            "secret": null,
            "setter": null,
            "stored": true,
            "subtype": null,
            "transient": null,
            "type": "enum",
            "unique": null,
            "uniqueScope": null
        }
    ],
    "children": [],
    "model": {
        "aliases": [],
        "create": null,
        "delete": true,
        "description": null,
        "entity_name": "Customer",
        "exposed": true,
        "extends": [
            "@identifiable-pk-stored"
        ],
        "get": true,
        "package": null,
        "private": null,
        "resource_name": "customers",
        "rest_name": "customer",
        "root": null,
        "update": false
    }
}