{
    "attributes": [
        {
            "autogenerated": true,
            "description": "Data contains all logs data.",
            "exposed": true,
            "name": "data",
            "read_only": true,
            "subtype": "logs",
            "type": "external"
        }
    ],
    "model": {
        "entity_name": "Log",
        "package": "highwind",
        "resource_name": "logs",
        "rest_name": "log"
    }
}
