# Model
model:
  rest_name: cloudgraphnode
  resource_name: cloudgraphnodes
  entity_name: CloudGraphNode
  package: pcn/infrastructure
  group: pcn/infrastructure
  description: "Returns a data structure representing the graph of all cloud nodes
    \nand their connections in a particular namespace."

# Attributes
attributes:
  v1:
  - name: node
    description: Refers to the nodes of the map.
    type: ref
    exposed: true
    subtype: cloudnode
    read_only: true
    extensions:
      refMode: pointer

  - name: policyIDs
    description: The ID of the policies that were used in the path.
    type: external
    exposed: true
    subtype: map[string]string
    autogenerated: true

  - name: policyNamespace
    description: The namespace of the policy.
    type: string
    exposed: true
    autogenerated: true

  - name: policyType
    description: The type of policy that determined forwarding from this node.
    type: enum
    exposed: true
    allowed_choices:
    - Route
    - ACL
    - SG
    - Identity
    autogenerated: true

  - name: routeTableIDs
    description: |-
      The list of route tables IDs that forwarding was based on for the internal path,
      if routing was
      performed.
    type: external
    exposed: true
    subtype: map[string]string
    autogenerated: true
