# Model
model:
  rest_name: authz
  resource_name: authz
  entity_name: Authz
  package: cid
  group: core/authorization
  description: This is an internal api that is used to resolve to api authorization.
  private: true

# Attributes
attributes:
  v1:
  - name: authorizedIdentities
    description: |-
      Limits roles/permissions the token can be used for. This is only given to reduce
      the existing set of policies. For instance if you have administrative role, you
      can ask for a token that will tell the policy engine to reduce the permission to
      what it given here.

      Declaring a permission you don't initially have according to the policy engine
      has no effect.
    type: list
    exposed: true
    subtype: string
    example_value:
    - '@auth:role=enforcer'

  - name: authorizedNamespace
    description: |-
      Limits the namespace the token can be used in. For instance if you have access
      to `ns1` and `/ns2`, you can ask for a token that will tell the policy engine to
      reduce the permission to what simply `/ns2`.

      Declaring a namespace you don't initially have according to the policy engine
      has no effect.
    type: string
    exposed: true
    example_value: /namespace

  - name: claims
    description: The list of verified claims.
    type: list
    exposed: true
    subtype: string
    required: true
    example_value:
    - '@auth:account=acme'
    - '@auth:realm=vince'

  - name: clientIP
    description: IP of the client.
    type: string
    exposed: true

  - name: error
    description: Return an eventual error.
    type: string
    exposed: true
    read_only: true
    autogenerated: true
    omit_empty: true

  - name: permissions
    description: |-
      If the parameter permissions=1 is set, targetIdentity and targetOperation are
      ignored and this attribute will contain all the permission for the given claims.
    type: external
    exposed: true
    subtype: map[string]map[string]bool
    read_only: true
    autogenerated: true
    omit_empty: true

  - name: targetNamespace
    description: description.
    type: string
    exposed: true
    required: true
    example_value: /acme
