# Model
model:
  rest_name: authz
  resource_name: authz
  entity_name: Authz
  package: cid
  group: core/authorization
  description: This is an internal api that is used to resolve to api authorization.
  private: true

# Attributes
attributes:
  v1:
  - name: authorized
    description: Return if the request should be authorized.
    type: boolean
    exposed: true
    read_only: true
    autogenerated: true

  - name: claims
    description: The list of verified claims.
    type: list
    exposed: true
    subtype: string
    example_value:
    - '@auth:account=acme'
    - '@auth:realm=vince'

  - name: clientIP
    description: IP of the client.
    type: string
    exposed: true

  - name: error
    description: Return an eventual error.
    type: string
    exposed: true
    read_only: true
    autogenerated: true

  - name: permissions
    description: |-
      If the parameter permissions=1 is set, targetIdentity and targetOperation are
      ignored and this attribute will contain all the permission for the given claims
      .
    type: external
    exposed: true
    subtype: map[string]map[string]bool

  - name: targetIdentity
    description: The identity.
    type: string
    exposed: true
    example_value: namespace

  - name: targetNamespace
    description: description.
    type: string
    exposed: true
    example_value: /acme

  - name: targetOperation
    description: Operation.
    type: enum
    exposed: true
    allowed_choices:
    - Any
    - Create
    - Delete
    - Info
    - Patch
    - Retrieve
    - RetrieveMany
    - Update
    example_value: Create
