# Model
model:
  rest_name: claims
  resource_name: claims
  entity_name: Claims
  package: guy
  group: policy/networking
  description: This API represents the claims that accessed a service.
  indexes:
  - - :shard
    - zone
    - zHash
  - - :unique
    - namespace
    - hash
  - - namespace
  - - namespace
    - hash
  - - namespace
    - normalizedTags
  get:
    description: Retrieves the object with the given ID.
  extends:
  - '@base'
  - '@identifiable-stored'
  - '@zonable'

# Attributes
attributes:
  v1:
  - name: content
    description: Content contains the raw JWT claims.
    type: external
    exposed: true
    subtype: map[string]string
    stored: true
    required: true
    creation_only: true
    example_value:
      exp: 1553899021
      iat: 1553888221
      iss: https://accounts.acme.com
      sub: alice@acme.com

  - name: firstSeen
    description: firstSeen contains the date of the first appearance of the claims.
    type: time
    stored: true
    read_only: true
    autogenerated: true

  - name: hash
    description: Unique hash of the claim access.
    type: string
    exposed: true
    stored: true
    required: true
    example_value: "1134423925458173049"

  - name: lastSeen
    description: lastSeen contains the date of the last appearance of the claims.
    type: time
    stored: true
    read_only: true
    autogenerated: true
