# Model
model:
  rest_name: cloudnetworkquerydestination
  resource_name: cloudnetworkquerydestinations
  entity_name: CloudNetworkQueryDestination
  package: pcn
  group: prisma/infrastructure
  description: Returns the set of discovered destinations and the associated verdicts.
  detached: true

# Attributes
attributes:
  v1:
  - name: IP
    description: The IP address of the destination if it is a public address.
    type: string
    exposed: true
    autogenerated: true

  - name: isPublicIP
    description: Returns true of this is just a public IP destination.
    type: boolean
    exposed: true
    autogenerated: true

  - name: nativeID
    description: The nativeID of the destination if it is a cloud node.
    type: string
    exposed: true
    autogenerated: true

  - name: reachable
    description: Returns true if the destination is reachable through routing.
    type: boolean
    exposed: true
    autogenerated: true

  - name: verdict
    description: Returns the network security verdict for the destination.
    type: string
    exposed: true
    autogenerated: true
