# Model
model:
  rest_name: enforcerrefresh
  resource_name: enforcerrefreshes
  entity_name: EnforcerRefresh
  package: gaga
  group: core/policy
  description: |-
    Sent to client when a poke has been triggered using the
    parameter `?notify=true`. This is used by instances of enforcerd to notify an
    external change on the processing unit must be processed.

# Attributes
attributes:
  v1:
  - name: ID
    description: Contains the ID of the target enforcer.
    type: string
    exposed: true
    read_only: true
    getter: true
    setter: true
    identifier: true

  - name: debug
    description: If set to true, start reporting debug information for the target
      enforcer.
    type: boolean
    exposed: true
    omit_empty: true

  - name: namespace
    description: Contains the original namespace of the enforcer.
    type: string
    exposed: true
    read_only: true
    autogenerated: true
