# Model
model:
  rest_name: hostservicemappingpolicy
  resource_name: hostservicemappingpolicies
  entity_name: HostServiceMappingPolicy
  package: squall
  description: |-
    Defines a host service mapping policy that provides the relation between
    enforcers and host services that they must implement.
  aliases:
  - hostsrvplc
  - hostsrvplcs
  get:
    description: Retrieves the object with the given ID.
  update:
    description: Updates the object with the given ID.
  delete:
    description: Deletes the object with the given ID.
    global_parameters:
    - $filtering
  extends:
  - '@base'
  - '@described'
  - '@disabled'
  - '@identifiable-nopk-nostored'
  - '@metadatable'
  - '@named'
  - '@propagated'
  - '@fallback'
  - '@schedulable'
  - '@zonable'

# Attributes
attributes:
  v1:
  - name: hostModeEnabled
    description: |-
      HostModeEnabled forces the corresponding enforcers to enable complete host
      protection. When this option is turned on, all incoming and outgoing flows will
      be monitored. Flows will be allowed if and only if a network policy has been
      created to allow the flow. The option applies to all enforcers that match the
      subject constraints.
    type: boolean
    exposed: true
    default_value: false
    orderable: true

  - name: hostservices
    description: |-
      Hostservices is the list of host services that the policy resolves to. This is a
      read only attribute after policy is resolved for a given enforcer.
    type: refList
    exposed: true
    subtype: hostservice
    read_only: true
    autogenerated: true

  - name: object
    description: |-
      Object of the policy is the selector for the host services that must be applied
      to this enforcer.
    type: external
    exposed: true
    subtype: policies_list
    orderable: true

  - name: subject
    description: |-
      Subject of the policy is the selector of the enforcers that the list of host
      services must apply to.
    type: external
    exposed: true
    subtype: policies_list
    orderable: true

# Relations
relations:
- rest_name: enforcer
  get:
    description: Returns the list of enforcers that are affected by this poliy.

- rest_name: hostservice
  get:
    description: Returns the list of host services that are referred by this policy.
