# Model
model:
  rest_name: importrequest
  resource_name: importrequests
  entity_name: ImportRequest
  package: vivi
  group: core
  description: |-
    This API allows to send a request for creating a bunch of objects to a
    namespace. The request will be sent to the desired namespace is API
    auhorizations permit it. An approver will then need to review the request and
    can eventually approve it, which will result in the creation of requested
    objects if he has the permission to do so.

    The Import Request is sent to the user namespace where he needs the permission
    to do so. The user must also set the `targetNamespace` attribute where he wants
    the objects to be created. He must also have the permission to do so in that
    namespace. Once all the appropriate check have been done, the Import request
    will be created in the `targetNamespace`.

    The requester will no be able to change anything once created unless the
    Approver sets the status to `ChangeRequested`.

    The Import request will reside in the target namespace. However, it will be
    visible from both the requester's namespace and the target namespace.
  aliases:
  - req
  - reqs
  - ireq
  - ireqs
  indexes:
  - - :shard
    - zone
    - zHash
  - - namespace
  - - namespace
    - name
  get:
    description: Retrieve a single existing import request.
  update:
    description: Update an existing import request.
  delete:
    description: Delete an existing import request.
  extends:
  - '@base'
  - '@described'
  - '@timeable'
  - '@identifiable-stored'
  - '@zonable'

# Attributes
attributes:
  v1:
  - name: data
    description: The data to import.
    type: external
    exposed: true
    subtype: map[string][]map[string]interface{}
    stored: true
    required: true
    creation_only: true
    example_value:
      networkaccesspolicies:
      - action: Allow
        description: Allows Acme to access service A
        logsEnabled: true
        name: allow-acme
        object:
        - - $identity=processingunit
          - $namespace=/acme/prod
          - app=query
        subject:
        - - $identity=processingunit
          - app=partner-data

  - name: requesterClaims
    description: |-
      The identity claims of the requester. This will be populated by the control
      plane.
    type: list
    exposed: true
    subtype: string
    stored: true
    read_only: true
    autogenerated: true
    example_value:
    - '@auth:realm=vince'
    - '@auth:account=acme'

  - name: requesterNamespace
    description: |-
      The namespace from the request was created. This will be populated by the
      control plane.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true

  - name: status
    description: |-
      The status of the request. The content of data can only be changed when the
      status is set to `ChangeRequested`. If the Status is set to `Approved` the data
      will be created immediately. If the status is set to `Rejected` the request
      cannot be changed anymore and ca be deleted. `Pending` and `Acknowledged` are
      just informational.
    type: enum
    exposed: true
    stored: true
    allowed_choices:
    - Pending
    - Acknowledged
    - ChangeRequested
    - Approved
    - Rejected
    default_value: Pending

  - name: targetNamespace
    description: |-
      The namespace where the request will be sent. The requester can set any
      namespace but he needs to have an autorization to post the request in that
      namespace.
    type: string
    exposed: true
    required: true
    creation_only: true
    example_value: /acme/prod
    transient: true
