# Model
model:
  rest_name: localauthority
  resource_name: localauthorities
  entity_name: LocalAuthority
  package: squall
  group: core/namespace
  description: |-
    Can be used to retrieve or renew the local and SSH certificate authorities of
    the namespace.

# Attributes
attributes:
  v1:
  - name: CA
    description: The certificate authority used by the namespace.
    type: string
    exposed: true
    read_only: true
    autogenerated: true
    transient: true

  - name: CARenew
    description: Set to `true` to renew the certificate authority of the namespace.
    type: boolean
    exposed: true
    read_only: true
    autogenerated: true
    transient: true

  - name: SSHCA
    description: The SSH certificate authority used by the namespace.
    type: string
    exposed: true
    read_only: true
    autogenerated: true
    transient: true

  - name: SSHCARenew
    description: Set to `true` to renew the SSH certificate authority of the namespace.
    type: boolean
    exposed: true
    read_only: true
    autogenerated: true
    transient: true
