# Model
model:
  rest_name: namespacetype
  resource_name: namespacetypes
  entity_name: NamespaceType
  package: squall
  group: core/namespace
  description: |-
    Returns the type of the current namespace (passed in the X-Namespace header).

# Attributes
attributes:
  v1:
  - name: type
    description: Type of namespace.
    type: string
    exposed: true
    read_only: true
    autogenerated: true
    transient: true
