# Model
model:
  rest_name: oauthinfo
  resource_name: oauthinfo
  entity_name: OAUTHInfo
  package: cactuar
  group: internal/oauth
  description: |-
    OAUTHInfo provides the information for an OAUTH server to retrieve the secrets
    that can validate a JWT token issued by us.
  get:
    description: Retrieves the OAUTH info.

# Attributes
attributes:
  v1:
  - name: auhorization_endpoint
    description: Authorization_Endpoint is the authorization endpoint.
    type: string
    exposed: true
    read_only: true
    autogenerated: true

  - name: claims_supported
    description: claims_supported is corresponding attribute of the OIDC spec.
    type: list
    exposed: true
    subtype: string
    read_only: true
    autogenerated: true

  - name: id_token_signing_alg_values_supported
    description: |-
      id_token_signing_alg_values_supported is corresponding attribute of the OIDC
      spec.
    type: list
    exposed: true
    subtype: string
    read_only: true
    autogenerated: true

  - name: issuer
    description: Issuer is the the URL pointing to the issuer of the token.
    type: string
    exposed: true
    read_only: true
    autogenerated: true

  - name: jwks_uri
    description: |-
      JWKS_URI is the URI that can be used to retrieve the public keys that will
      verify a JWT.
    type: string
    exposed: true
    read_only: true
    autogenerated: true

  - name: response_types_supported
    description: Response_Types_Supported is corresponding attribute of the OIDC spec.
    type: list
    exposed: true
    subtype: string
    read_only: true
    autogenerated: true

  - name: scopes_supported
    description: scopes_supported is corresponding attribute of the OIDC spec.
    type: list
    exposed: true
    subtype: string
    read_only: true
    autogenerated: true

  - name: subject_types_supported
    description: Subject_Types_Supported is corresponding attribute of the OIDC spec.
    type: list
    exposed: true
    subtype: string
    read_only: true
    autogenerated: true

  - name: token_endpoint_auth_methods_supported
    description: |-
      token_endpoint_auth_methods_supported is corresponding attribute of the OIDC
      spec.
    type: list
    exposed: true
    subtype: string
    read_only: true
    autogenerated: true
