# Model
model:
  rest_name: oauthinfo
  resource_name: oauthinfo
  entity_name: OAUTHInfo
  package: squall
  group: internal/oauth
  description: |-
    OAUTHInfo provides the information for an OAUTH server to retrieve the secrets
    that can validate a JWT token issued by us.

# Attributes
attributes:
  v1:
  - name: jwks_uri
    description: |-
      JWKS_URI is the URI that can be used to retrieve the public keys that will
      verify a JWT.
    type: string
    exposed: true
    read_only: true
    autogenerated: true

  - name: keys
    description: Keys is a list of keys that can be used to verify a JWT.
    type: refMap
    exposed: true
    subtype: jwks
    read_only: true
    autogenerated: true
    extensions:
      refMode: pointer
