# Model
model:
  rest_name: oauthinfo
  resource_name: oauthinfo
  entity_name: OAUTHInfo
  package: cactuar
  group: internal/oauth
  description: |-
    OAUTHInfo provides the information for an OAUTH server to retrieve the secrets
    that can validate a JWT token issued by us.
  get:
    description: Retrieves the OAUTH info.

# Attributes
attributes:
  v1:
  - name: jwks_uri
    description: |-
      JWKS_URI is the URI that can be used to retrieve the public keys that will
      verify a JWT.
    type: string
    exposed: true
    read_only: true
    autogenerated: true

  - name: keyString
    description: |-
      keyString is the JWKS key response for an OAUTH verifier. It provides the OAUTH
      compatible string and not a structure that can be marshalled.
    type: string
    exposed: true
    read_only: true
    autogenerated: true
