# Model
model:
  rest_name: pingrequest
  resource_name: pingrequests
  entity_name: PingRequest
  package: guy
  group: core
  description: Post a new pu pingrequest.

# Attributes
attributes:
  v1:
  - name: iterations
    description: Number of probes that will be triggered.
    type: integer
    exposed: true
    stored: true

  - name: pingID
    description: Unique ID generated for each ping request.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true
