# Model
model:
  rest_name: privatekey
  resource_name: privatekey
  entity_name: PrivateKey
  package: squall
  group: internal/x509
  description: Manages private keys.
  private: true
  get:
    description: Retrieves a private key information.
    global_parameters:
    - $propagatable
  update:
    description: Updates a private key.
  delete:
    description: Deletes a private key.
  extends:
  - '@base'
  - '@zoned'
  - '@namespaced'
  - '@described'
  - '@identifiable-stored'
  - '@named'
  - '@propagated'
  - '@timeable'

# Indexes
indexes:
- - namespace
  - fingerprint
- - fingerprint

# Attributes
attributes:
  v1:
  - name: fingerprint
    description: The fingerprint of the private key.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true

  - name: key
    description: Private key in PEM format.
    type: string
    exposed: true
    stored: true
    required: true
    creation_only: true
    example_value: |-
      -----BEGIN PRIVATE KEY-----
      MIIBsjCCAVigAwIBAgIQCjRniVLvvHhekhI3H7+m8DAKBggqhkjOPQQDAjBGMRAw
      DgYDVQQKEwdBcG9yZXRvMQ8wDQYDVQQLEwZhcG9tdXgxITAfBgNVBAMTGEFwb211
      eCBQdWJsaWMgU2lnbmluZyBDQTAeFw0xODAxMTcwNjUzNTFaFw0yNzExMjYwNjUz
      NTFaMDkxETAPBgNVBAoTCGFwb3Rlc3RzMREwDwYDVQQLEwhhcG90ZXN0czERMA8G
      A1UEAxMIYXBvdGVzdHMwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASJsYjvdkaf
      qE/TL/eQETmIl8uFgqJi2LumYgEjHPHLlz8fJzDP12yQsqgOPymqmFCjmnVsdxcW
      YbXTwQzWW5kwozUwMzAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAwwCgYIKwYBBQUH
      AwIwDAYDVR0TAQH/BAIwADAKBggqhkjOPQQDAgNIADBFAiEAgNxYC2hMqll3aTS8
      oBbFevZHAV5p0nyzRNj2pFrHEaQCIG4A9zKzE2f8g3zEaKcQNZ3Bxrk/T+hcJxaG
      Mlri6/+4
      -----END PRIVATE KEY-----
    secret: true
    encrypted: true

