# Model
model:
  rest_name: rendernamespace
  resource_name: rendernamespaces
  entity_name: RenderNamespace
  package: squall
  group: core/namespace
  description: |-
    This object allows you to determine which namespace an object should reside in
    based on the tags provided.
  aliases:
  - renderns

# Attributes
attributes:
  v1:
  - name: namespace
    description: The namespace where the object should reside in.
    type: string
    exposed: true
    read_only: true
    autogenerated: true

  - name: tags
    description: List of tags of the object to render the namespace for.
    type: list
    exposed: true
    subtype: string
    required: true
    example_value:
    - a=a
    - b=b
