# Model
model:
  rest_name: reportsquery
  resource_name: reportsqueries
  entity_name: ReportsQuery
  package: jenova
  group: visualization/reportsquery
  description: |-
    Supports querying Aporeto reports. All queries are protected within the
    namespace of the user.
  aliases:
  - rq

# Attributes
attributes:
  v1:
  - name: report
    description: Name of the report type to query.
    type: enum
    exposed: true
    allowed_choices:
    - Flows
    - Audit
    - Enforcers
    - Files
    - EventLogs
    - Packets
    - Counters
    - Accesses
    - DNSLookups
    default_value: Flows

  - name: results
    description: Contains the result of the query.
    type: ref
    exposed: true
    subtype: reportsqueryresults
    read_only: true
    autogenerated: true
    extensions:
      refMode: pointer
