# Model
model:
  rest_name: servicecertificate
  resource_name: servicecertificates
  entity_name: ServiceCertificate
  package: squall
  group: internal/x509
  description: Manages private keys.
  get:
    description: Retrieves a service certificate's information.
    global_parameters:
    - $propagatable
  update:
    description: Updates a service certificate.
  delete:
    description: Deletes a service certificate.
  extends:
  - '@base'
  - '@zoned'
  - '@namespaced'
  - '@described'
  - '@identifiable-stored'
  - '@named'
  - '@propagated'
  - '@timeable'

# Indexes
indexes:
- - namespace
  - fingerprint
- - fingerprint

# Attributes
attributes:
  v1:
  - name: fingerprint
    description: The fingerprint of the public key.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true

  - name: private
    description: Private key in PEM format.
    type: string
    exposed: true
    stored: true
    required: true
    example_value: |-
      -----BEGIN EC PRIVATE KEY-----
      MHcCAQEEIHjrDddXMasytnPC2+7m2BnkgEX7a6Vk1G13dQsASpAhoAoGCCqGSM49
      AwEHoUQDQgAEBzbAGpf40lZVupONiSmjKcK4BS6hxk41LGXXsTa2kztqhkm+sfV+
      8kwyOG9ewI4GDHgT/6rwX3GEIudglZ6ecQ==
      -----END EC PRIVATE KEY-----
    secret: true
    transient: true
    encrypted: true
    validations:
    - $pem

  - name: public
    description: Public key in PEM format.
    type: string
    exposed: true
    stored: true
    required: true
    example_value: |-
      -----BEGIN CERTIFICATE-----
      MIIBKjCB0aADAgECAhEAugDV416p70g1FGz9A91H4DAKBggqhkjOPQQDAjAOMQww
      CgYDVQQDEwNjdWwwHhcNMjEwNzA2MTYzMjI4WhcNMjIwNzAxMTYzMjI4WjAOMQww
      CgYDVQQDEwNjdWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQHNsAal/jSVlW6
      k42JKaMpwrgFLqHGTjUsZdexNraTO2qGSb6x9X7yTDI4b17AjgYMeBP/qvBfcYQi
      52CVnp5xoxAwDjAMBgNVHRMBAf8EAjAAMAoGCCqGSM49BAMCA0gAMEUCICZcMM89
      fJz9LMdpz/A1RpBEC0Xx4I/8JWrHroVYPOG7AiEA37iWAAi1DYBboyxevbCc6kNa
      Su0pBE163iBEKUew0/s=
      -----END CERTIFICATE-----
    validations:
    - $pem
