package gaia

import (
	"fmt"
	"sync"

	"github.com/aporeto-inc/elemental"
	"time"
)

// InvoiceIdentity represents the Identity of the object.
var InvoiceIdentity = elemental.Identity{
	Name:     "invoice",
	Category: "invoices",
	Private:  false,
}

// InvoicesList represents a list of Invoices
type InvoicesList []*Invoice

// ContentIdentity returns the identity of the objects in the list.
func (o InvoicesList) ContentIdentity() elemental.Identity {

	return InvoiceIdentity
}

// Copy returns a pointer to a copy the InvoicesList.
func (o InvoicesList) Copy() elemental.ContentIdentifiable {

	copy := append(InvoicesList{}, o...)
	return &copy
}

// Append appends the objects to the a new copy of the InvoicesList.
func (o InvoicesList) Append(objects ...elemental.Identifiable) elemental.ContentIdentifiable {

	out := append(InvoicesList{}, o...)
	for _, obj := range objects {
		out = append(out, obj.(*Invoice))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o InvoicesList) List() elemental.IdentifiablesList {

	out := elemental.IdentifiablesList{}
	for _, item := range o {
		out = append(out, item)
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o InvoicesList) DefaultOrder() []string {

	return []string{}
}

// Version returns the version of the content.
func (o InvoicesList) Version() int {

	return 1
}

// Invoice represents the model of a invoice
type Invoice struct {
	// AccountID is the identity of the customer for this invoice.
	AccountID string `json:"accountID" bson:"accountid" mapstructure:"accountID,omitempty"`

	// endTime specifies the end time for this invoice.
	EndTime time.Time `json:"endTime" bson:"endtime" mapstructure:"endTime,omitempty"`

	// startTime specifies the start time for the invoice.
	StartTime time.Time `json:"startTime" bson:"starttime" mapstructure:"startTime,omitempty"`

	// totalCost specifies the total amount to be billed to the customer in dollars.
	TotalCost int `json:"totalCost" bson:"totalcost" mapstructure:"totalCost,omitempty"`

	// unitPrice specifies the billing rate per unit in cents.
	UnitPrice int `json:"unitPrice" bson:"unitprice" mapstructure:"unitPrice,omitempty"`

	// unitsConsumed provides the number of units consumed.
	UnitsConsumed int `json:"unitsConsumed" bson:"unitsconsumed" mapstructure:"unitsConsumed,omitempty"`

	// ID is the identifier of the object.
	ID string `json:"ID" bson:"_id" mapstructure:"ID,omitempty"`

	// Creation date of the object.
	CreateTime time.Time `json:"createTime" bson:"createtime" mapstructure:"createTime,omitempty"`

	// Last update date of the object
	UpdateTime time.Time `json:"updateTime" bson:"updatetime" mapstructure:"updateTime,omitempty"`

	ModelVersion int `json:"-" bson:"_modelversion"`

	sync.Mutex
}

// NewInvoice returns a new *Invoice
func NewInvoice() *Invoice {

	return &Invoice{
		ModelVersion: 1,
	}
}

// Identity returns the Identity of the object.
func (o *Invoice) Identity() elemental.Identity {

	return InvoiceIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *Invoice) Identifier() string {

	return o.ID
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *Invoice) SetIdentifier(id string) {

	o.ID = id
}

// Version returns the hardcoded version of the model.
func (o *Invoice) Version() int {

	return 1
}

// DefaultOrder returns the list of default ordering fields.
func (o *Invoice) DefaultOrder() []string {

	return []string{}
}

func (o *Invoice) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// Validate valides the current information stored into the structure.
func (o *Invoice) Validate() error {

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if err := elemental.ValidateRequiredString("accountID", o.AccountID); err != nil {
		requiredErrors = append(requiredErrors, err)
	}

	if err := elemental.ValidateRequiredString("accountID", o.AccountID); err != nil {
		errors = append(errors, err)
	}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*Invoice) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := InvoiceAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return InvoiceLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*Invoice) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return InvoiceAttributesMap
}

// InvoiceAttributesMap represents the map of attribute for Invoice.
var InvoiceAttributesMap = map[string]elemental.AttributeSpecification{
	"ID": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		ConvertedName:  "ID",
		Description:    `ID is the identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		PrimaryKey:     true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
		Unique:         true,
	},
	"AccountID": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		ConvertedName:  "AccountID",
		Description:    `AccountID is the identity of the customer for this invoice.`,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "accountID",
		Orderable:      true,
		ReadOnly:       true,
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"CreateTime": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		ConvertedName:  "CreateTime",
		Description:    `Creation date of the object.`,
		Exposed:        true,
		Filterable:     true,
		Name:           "createTime",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "time",
	},
	"EndTime": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		ConvertedName:  "EndTime",
		Description:    `endTime specifies the end time for this invoice.`,
		Exposed:        true,
		Name:           "endTime",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "time",
	},
	"StartTime": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		ConvertedName:  "StartTime",
		Description:    `startTime specifies the start time for the invoice.`,
		Exposed:        true,
		Name:           "startTime",
		ReadOnly:       true,
		Stored:         true,
		Type:           "time",
	},
	"TotalCost": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		ConvertedName:  "TotalCost",
		Description:    `totalCost specifies the total amount to be billed to the customer in dollars.`,
		Exposed:        true,
		Name:           "totalCost",
		ReadOnly:       true,
		Stored:         true,
		Type:           "integer",
	},
	"UnitPrice": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		ConvertedName:  "UnitPrice",
		Description:    `unitPrice specifies the billing rate per unit in cents.`,
		Exposed:        true,
		Name:           "unitPrice",
		ReadOnly:       true,
		Stored:         true,
		Type:           "integer",
	},
	"UnitsConsumed": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		ConvertedName:  "UnitsConsumed",
		Description:    `unitsConsumed provides the number of units consumed.`,
		Exposed:        true,
		Name:           "unitsConsumed",
		ReadOnly:       true,
		Stored:         true,
		Type:           "integer",
	},
	"UpdateTime": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		ConvertedName:  "UpdateTime",
		Description:    `Last update date of the object`,
		Exposed:        true,
		Filterable:     true,
		Name:           "updateTime",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "time",
	},
}

// InvoiceLowerCaseAttributesMap represents the map of attribute for Invoice.
var InvoiceLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"id": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		ConvertedName:  "ID",
		Description:    `ID is the identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		PrimaryKey:     true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
		Unique:         true,
	},
	"accountid": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		ConvertedName:  "AccountID",
		Description:    `AccountID is the identity of the customer for this invoice.`,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "accountID",
		Orderable:      true,
		ReadOnly:       true,
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"createtime": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		ConvertedName:  "CreateTime",
		Description:    `Creation date of the object.`,
		Exposed:        true,
		Filterable:     true,
		Name:           "createTime",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "time",
	},
	"endtime": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		ConvertedName:  "EndTime",
		Description:    `endTime specifies the end time for this invoice.`,
		Exposed:        true,
		Name:           "endTime",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "time",
	},
	"starttime": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		ConvertedName:  "StartTime",
		Description:    `startTime specifies the start time for the invoice.`,
		Exposed:        true,
		Name:           "startTime",
		ReadOnly:       true,
		Stored:         true,
		Type:           "time",
	},
	"totalcost": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		ConvertedName:  "TotalCost",
		Description:    `totalCost specifies the total amount to be billed to the customer in dollars.`,
		Exposed:        true,
		Name:           "totalCost",
		ReadOnly:       true,
		Stored:         true,
		Type:           "integer",
	},
	"unitprice": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		ConvertedName:  "UnitPrice",
		Description:    `unitPrice specifies the billing rate per unit in cents.`,
		Exposed:        true,
		Name:           "unitPrice",
		ReadOnly:       true,
		Stored:         true,
		Type:           "integer",
	},
	"unitsconsumed": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		ConvertedName:  "UnitsConsumed",
		Description:    `unitsConsumed provides the number of units consumed.`,
		Exposed:        true,
		Name:           "unitsConsumed",
		ReadOnly:       true,
		Stored:         true,
		Type:           "integer",
	},
	"updatetime": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		ConvertedName:  "UpdateTime",
		Description:    `Last update date of the object`,
		Exposed:        true,
		Filterable:     true,
		Name:           "updateTime",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "time",
	},
}
